---
# enum

- name: enum coreos virtual machines
  shell: |
    BRIDGE=virbr0
    MAC=$(virsh dumpxml "{{ item.key }}" | awk -F\' '/mac address/ {print $2}')
    while true
    do
        IP=$(grep -B1 $MAC /var/lib/libvirt/dnsmasq/$BRIDGE.status | head \
             -n 1 | awk '{print $2}' | sed -e s/\"//g -e s/,//)
        if [ "$IP" = "" ]
        then
            sleep 1
        else
            break
        fi
    done

    echo "$(date -R) DONE. SSH to "{{ item.key }}" using ssh core@$IP" >> ip.md
  with_dict: "{{ vms }}"
